In [2]:
import pandas as pd

df=pd.read_csv('C:\\Users\\ADMIN\\Desktop\\merge.csv')

In [3]:
df

cst_id_di  MRC_ID_DI   VAR002  VAR003   VAR004   VAR005   VAR006  \
0      90000000089          0 -0.06610  0.5280 -0.13607  0.10945  0.06557   
1      90000000176          8 -0.09537  0.1347 -0.13541  0.17331 -0.19657   
2      90000000210          0 -0.01048  0.8360  0.37797 -0.10970  0.52032   
3      90000000212          5  0.05194  0.7505  0.04611 -0.16512  0.07413   
4      90000000213          6 -0.08536  0.3767 -0.12288  0.10023 -0.43414   
...            ...        ...      ...     ...      ...      ...      ...   
10119  90000460112          7 -0.06606  0.6615 -0.09743 -0.03240  0.10111   
10120  90000460117          0 -0.03031  0.0143  0.07041 -0.02519  0.58013   
10121  90000460233          0 -0.05351  0.3121  0.36925 -0.10039  0.51159   
10122  90000460310          0 -0.00562  0.2286  0.04581 -0.05390  0.20481   
10123  90000460313          0 -0.06814  0.6968 -0.04318  0.11340 -0.08842   

       VAR007  VAR008   VAR009  ...   VAR218   VAR219   VAR220   VAR221  \
0           0  0.7702 -0.18965  ... -0.32829  0.19113  0.05449  0.09471   
1           0  0.0616 -0.23104  ... -0.23729  0.19437  0.06538  0.16309   
2           1  0.3257  0.32632  ...  0.53283 -0.52084 -0.18568 -0.09755   
3           0  0.5322  0.26845  ...  0.20754 -0.01934 -0.05172 -0.13245   
4           0  0.5468 -0.25575  ... -0.42251  0.23122  0.07913  0.09206   
...       ...     ...      ...  ...      ...      ...      ...      ...   
10119       0  0.9722 -0.02041  ... -0.19780  0.33881 -0.01692 -0.01823   
10120       0  0.0330  0.06676  ...  0.09259 -0.19384 -0.02383 -0.02448   
10121       0  0.2582  0.35016  ...  0.46478 -0.45312 -0.17163 -0.08674   
10122       0  0.5957  0.11319  ...  0.10340  0.01754 -0.01479 -0.03898   
10123       0  0.1151 -0.02036  ...  0.00564  0.08257  0.00120  0.08881   

        VAR222   VAR223   VAR224   VAR225   VAR226   VAR227  
0      0.27091  0.01931  0.02938  0.17105  0.12537  0.22197  
1      0.30207  0.06053 -0.01107  0.12413  0.29702 -0.31717  
2     -0.56565 -0.17840 -0.06314 -0.17111 -0.32239  0.33962  
3     -0.16357 -0.05697  0.01587 -0.04022  0.31213 -0.00559  
4      0.46971  0.07964 -0.04698  0.03581  0.22588 -0.34868  
...        ...      ...      ...      ...      ...      ...  
10119  0.21720 -0.08346 -0.07835  0.02321  0.32967 -0.25995  
10120 -0.05019 -0.02869 -0.05401  0.01670 -0.15880  0.48301  
10121 -0.40260 -0.15903 -0.10292 -0.11742 -0.31895  0.40357  
10122 -0.01363  0.06974 -0.03815 -0.04371  0.11433 -0.01931  
10123  0.01272 -0.01391 -0.05940  0.44214  0.22888 -0.09918  

[10124 rows x 228 columns]

In [4]:
#머신러닝 예제 보면서 예제 다 해보기 

import numpy as np

In [7]:
df.loc[:,'MRC_ID_DI']

0        0
1        8
2        0
3        5
4        6
        ..
10119    7
10120    0
10121    0
10122    0
10123    0
Name: MRC_ID_DI, Length: 10124, dtype: int64

In [8]:
df.loc[:,'VAR002':]

VAR002  VAR003   VAR004   VAR005   VAR006  VAR007  VAR008   VAR009  \
0     -0.06610  0.5280 -0.13607  0.10945  0.06557       0  0.7702 -0.18965   
1     -0.09537  0.1347 -0.13541  0.17331 -0.19657       0  0.0616 -0.23104   
2     -0.01048  0.8360  0.37797 -0.10970  0.52032       1  0.3257  0.32632   
3      0.05194  0.7505  0.04611 -0.16512  0.07413       0  0.5322  0.26845   
4     -0.08536  0.3767 -0.12288  0.10023 -0.43414       0  0.5468 -0.25575   
...        ...     ...      ...      ...      ...     ...     ...      ...   
10119 -0.06606  0.6615 -0.09743 -0.03240  0.10111       0  0.9722 -0.02041   
10120 -0.03031  0.0143  0.07041 -0.02519  0.58013       0  0.0330  0.06676   
10121 -0.05351  0.3121  0.36925 -0.10039  0.51159       0  0.2582  0.35016   
10122 -0.00562  0.2286  0.04581 -0.05390  0.20481       0  0.5957  0.11319   
10123 -0.06814  0.6968 -0.04318  0.11340 -0.08842       0  0.1151 -0.02036   

       VAR010   VAR011  ...   VAR218   VAR219   VAR220   VAR221   VAR222  \
0      0.1981  0.24149  ... -0.32829  0.19113  0.05449  0.09471  0.27091   
1      0.4940 -0.39476  ... -0.23729  0.19437  0.06538  0.16309  0.30207   
2      0.7343  0.73494  ...  0.53283 -0.52084 -0.18568 -0.09755 -0.56565   
3      0.7327  0.32617  ...  0.20754 -0.01934 -0.05172 -0.13245 -0.16357   
4      0.9644 -0.52948  ... -0.42251  0.23122  0.07913  0.09206  0.46971   
...       ...      ...  ...      ...      ...      ...      ...      ...   
10119  0.6966  0.06993  ... -0.19780  0.33881 -0.01692 -0.01823  0.21720   
10120  0.8251  0.68992  ...  0.09259 -0.19384 -0.02383 -0.02448 -0.05019   
10121  0.4638  0.68799  ...  0.46478 -0.45312 -0.17163 -0.08674 -0.40260   
10122  0.2527  0.42924  ...  0.10340  0.01754 -0.01479 -0.03898 -0.01363   
10123  0.8465  0.13615  ...  0.00564  0.08257  0.00120  0.08881  0.01272   

        VAR223   VAR224   VAR225   VAR226   VAR227  
0      0.01931  0.02938  0.17105  0.12537  0.22197  
1      0.06053 -0.01107  0.12413  0.29702 -0.31717  
2     -0.17840 -0.06314 -0.17111 -0.32239  0.33962  
3     -0.05697  0.01587 -0.04022  0.31213 -0.00559  
4      0.07964 -0.04698  0.03581  0.22588 -0.34868  
...        ...      ...      ...      ...      ...  
10119 -0.08346 -0.07835  0.02321  0.32967 -0.25995  
10120 -0.02869 -0.05401  0.01670 -0.15880  0.48301  
10121 -0.15903 -0.10292 -0.11742 -0.31895  0.40357  
10122  0.06974 -0.03815 -0.04371  0.11433 -0.01931  
10123 -0.01391 -0.05940  0.44214  0.22888 -0.09918  

[10124 rows x 226 columns]

In [10]:
df.iloc[:,1]

0        0
1        8
2        0
3        5
4        6
        ..
10119    7
10120    0
10121    0
10122    0
10123    0
Name: MRC_ID_DI, Length: 10124, dtype: int64

In [11]:
df.iloc[:,2:]

VAR002  VAR003   VAR004   VAR005   VAR006  VAR007  VAR008   VAR009  \
0     -0.06610  0.5280 -0.13607  0.10945  0.06557       0  0.7702 -0.18965   
1     -0.09537  0.1347 -0.13541  0.17331 -0.19657       0  0.0616 -0.23104   
2     -0.01048  0.8360  0.37797 -0.10970  0.52032       1  0.3257  0.32632   
3      0.05194  0.7505  0.04611 -0.16512  0.07413       0  0.5322  0.26845   
4     -0.08536  0.3767 -0.12288  0.10023 -0.43414       0  0.5468 -0.25575   
...        ...     ...      ...      ...      ...     ...     ...      ...   
10119 -0.06606  0.6615 -0.09743 -0.03240  0.10111       0  0.9722 -0.02041   
10120 -0.03031  0.0143  0.07041 -0.02519  0.58013       0  0.0330  0.06676   
10121 -0.05351  0.3121  0.36925 -0.10039  0.51159       0  0.2582  0.35016   
10122 -0.00562  0.2286  0.04581 -0.05390  0.20481       0  0.5957  0.11319   
10123 -0.06814  0.6968 -0.04318  0.11340 -0.08842       0  0.1151 -0.02036   

       VAR010   VAR011  ...   VAR218   VAR219   VAR220   VAR221   VAR222  \
0      0.1981  0.24149  ... -0.32829  0.19113  0.05449  0.09471  0.27091   
1      0.4940 -0.39476  ... -0.23729  0.19437  0.06538  0.16309  0.30207   
2      0.7343  0.73494  ...  0.53283 -0.52084 -0.18568 -0.09755 -0.56565   
3      0.7327  0.32617  ...  0.20754 -0.01934 -0.05172 -0.13245 -0.16357   
4      0.9644 -0.52948  ... -0.42251  0.23122  0.07913  0.09206  0.46971   
...       ...      ...  ...      ...      ...      ...      ...      ...   
10119  0.6966  0.06993  ... -0.19780  0.33881 -0.01692 -0.01823  0.21720   
10120  0.8251  0.68992  ...  0.09259 -0.19384 -0.02383 -0.02448 -0.05019   
10121  0.4638  0.68799  ...  0.46478 -0.45312 -0.17163 -0.08674 -0.40260   
10122  0.2527  0.42924  ...  0.10340  0.01754 -0.01479 -0.03898 -0.01363   
10123  0.8465  0.13615  ...  0.00564  0.08257  0.00120  0.08881  0.01272   

        VAR223   VAR224   VAR225   VAR226   VAR227  
0      0.01931  0.02938  0.17105  0.12537  0.22197  
1      0.06053 -0.01107  0.12413  0.29702 -0.31717  
2     -0.17840 -0.06314 -0.17111 -0.32239  0.33962  
3     -0.05697  0.01587 -0.04022  0.31213 -0.00559  
4      0.07964 -0.04698  0.03581  0.22588 -0.34868  
...        ...      ...      ...      ...      ...  
10119 -0.08346 -0.07835  0.02321  0.32967 -0.25995  
10120 -0.02869 -0.05401  0.01670 -0.15880  0.48301  
10121 -0.15903 -0.10292 -0.11742 -0.31895  0.40357  
10122  0.06974 -0.03815 -0.04371  0.11433 -0.01931  
10123 -0.01391 -0.05940  0.44214  0.22888 -0.09918  

[10124 rows x 226 columns]

In [14]:
x=df.loc[:,'VAR002':]
y=df.loc[:,'MRC_ID_DI']
print(x.shape, y.shape)

(10124, 226) (10124,)


In [15]:
from sklearn.model_selection import train_test_split

# 데이터 나누기 - 6:2:2 비율
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=1)

print(x_train.shape, x_val.shape, x_test.shape)

(6074, 226) (2025, 226) (2025, 226)


## SVM

In [16]:
from sklearn.svm import SVC

In [17]:
# linear SVM 학습하기
linear_svm = SVC(kernel='linear')
linear_svm.fit(x_train, y_train)

SVC(kernel='linear')

In [18]:
# linear SVM accuracy 계산하기
from sklearn.metrics import accuracy_score, confusion_matrix
pred_val = linear_svm.predict(x_val)
print(f"accuracy:{accuracy_score(y_val, pred_val)}")

accuracy:0.8182716049382716


In [20]:
# 여러 가지 kernel을 사용해 SVM 학습하고 accuracy 계산하기
kernels = ['poly','rbf','sigmoid']

for kernel in kernels:
    print("==========================================") 
    model = SVC(kernel = kernel)
    model.fit(x_train, y_train)
    pred_val = model.predict(x_val)
    print(f"accuracy of {kernel}: {accuracy_score(y_val, pred_val)}")


accuracy of poly: 0.8182716049382716
accuracy of rbf: 0.8182716049382716
accuracy of sigmoid: 0.8093827160493827


In [21]:
# 각 조합에 대해 SVM 학습하고 accuracy 계산하기
C = [1, 10, 100, 1000]
Gamma = [0.00001, 0.0001, 0.001, 0.01]

for c in C:
    for gamma in Gamma:
        print("======================================")
        model = SVC(kernel = 'rbf', C=c, gamma=gamma)
        model.fit(x_train, y_train)
        pred_val = model.predict(x_val)
        print(f"accuracy of C={c}, gamma={gamma}: {accuracy_score(y_val, pred_val)}")
        

accuracy of C=1, gamma=1e-05: 0.8182716049382716
accuracy of C=1, gamma=0.0001: 0.8182716049382716
accuracy of C=1, gamma=0.001: 0.8182716049382716
accuracy of C=1, gamma=0.01: 0.8182716049382716
accuracy of C=10, gamma=1e-05: 0.8182716049382716
accuracy of C=10, gamma=0.0001: 0.8182716049382716
accuracy of C=10, gamma=0.001: 0.8182716049382716
accuracy of C=10, gamma=0.01: 0.8182716049382716
accuracy of C=100, gamma=1e-05: 0.8182716049382716
accuracy of C=100, gamma=0.0001: 0.8182716049382716
accuracy of C=100, gamma=0.001: 0.8182716049382716
accuracy of C=100, gamma=0.01: 0.817283950617284
accuracy of C=1000, gamma=1e-05: 0.8182716049382716
accuracy of C=1000, gamma=0.0001: 0.8182716049382716
accuracy of C=1000, gamma=0.001: 0.8187654320987654
accuracy of C=1000, gamma=0.01: 0.7822222222222223


In [22]:
from sklearn.model_selection import GridSearchCV

# GridSearchCV에서 cross validation을 하므로, validation data가 필요없음
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# 아래와 같이 탐색할 조합들을 지정
param_grid = {'C': [1, 10, 100, 1000], 
              'gamma': [0.00001, 0.0001, 0.001, 0.01]}

In [23]:
# GridSearchCV를 이용하여 분류하기
svm_grid = GridSearchCV(estimator=SVC(), param_grid=param_grid, cv=4, scoring='accuracy')
svm_grid.fit(x_train, y_train)

GridSearchCV(cv=4, estimator=SVC(),
             param_grid={'C': [1, 10, 100, 1000],
                         'gamma': [1e-05, 0.0001, 0.001, 0.01]},
             scoring='accuracy')

In [24]:
# 최적의 조합과 그 때의 점수 알아보기
print(svm_grid.best_params_)
print(svm_grid.best_score_)

{'C': 1, 'gamma': 1e-05}
0.8101000341580051


In [25]:
# test data에 대한 정확도 계산하기
pred_test2 = svm_grid.best_estimator_.predict(x_test)
print(f'test accuracy of rbf SVM grid: {accuracy_score(y_test, pred_test2)}')

test accuracy of rbf SVM grid: 0.8093827160493827


## Decision Tree

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
# 의사결정 나무 모델 학습하기
tree = DecisionTreeClassifier()
tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [28]:
# training accuracy 및 confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
print("training accuracy: ", accuracy_score(y_train, tree.predict(x_train)))
confusion_matrix(y_train, tree.predict(x_train))

training accuracy:  1.0


array([[6561,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,   68,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,   12,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,   22,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    9,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,  116,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  438,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,  536,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,  272,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,   40,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   25]],
      dtype=int64)

In [29]:
# validation accuracy 및 confusion matrix
print("validation accuracy: ", accuracy_score(y_val, tree.predict(x_val)))
confusion_matrix(y_val, tree.predict(x_val))

validation accuracy:  1.0


array([[1657,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,   12,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    2,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    4,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    3,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   31,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  108,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,  128,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   61,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,   13,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    6]],
      dtype=int64)

In [30]:
#training과 validation 성능 차이를 줄일 수 있는 간단한 방법
pruned_tree = DecisionTreeClassifier(max_depth=4, min_samples_leaf=3)
pruned_tree.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=4, min_samples_leaf=3)

In [31]:
print("training accuracy: ", accuracy_score(y_train, pruned_tree.predict(x_train)))
confusion_matrix(y_train, pruned_tree.predict(x_train))

training accuracy:  0.8112112606494629


array([[6542,    0,    0,    0,    0,    0,    2,   17,    0,    0,    0],
       [  64,    3,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [  12,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  22,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   9,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [ 113,    0,    0,    0,    0,    0,    0,    3,    0,    0,    0],
       [ 426,    2,    0,    0,    0,    0,    5,    5,    0,    0,    0],
       [ 513,    0,    0,    0,    0,    0,    3,   20,    0,    0,    0],
       [ 267,    1,    0,    0,    0,    0,    3,    1,    0,    0,    0],
       [  39,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [  24,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0]],
      dtype=int64)

In [32]:
print("validation accuracy: ", accuracy_score(y_val, pruned_tree.predict(x_val)))
confusion_matrix(y_val, pruned_tree.predict(x_val))

validation accuracy:  0.8192592592592592


array([[1652,    0,    0,    0,    0,    0,    0,    5,    0,    0,    0],
       [  11,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   4,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   3,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  30,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [ 107,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [ 122,    0,    0,    0,    0,    0,    0,    6,    0,    0,    0],
       [  60,    0,    0,    0,    0,    0,    1,    0,    0,    0,    0],
       [  13,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   6,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int64)

In [59]:
print("test accuracy: ", accuracy_score(y_test, pruned_tree.predict(x_test)))
confusion_matrix(y_test, pruned_tree.predict(x_test))

test accuracy:  0.8093827160493827


array([[1633,    0,    0,    0,    0,    0,    2,    4,    0,    0,    0],
       [  17,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   9,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [   2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  26,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [ 113,    0,    0,    0,    0,    0,    3,    0,    0,    0,    0],
       [ 122,    0,    0,    0,    0,    0,    0,    3,    0,    0,    0],
       [  65,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  18,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0],
       [   3,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int64)

## Linear Regression

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
# 데이터 나누기 - 6:2:2 비율
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=1)

print(x_train.shape, x_val.shape, x_test.shape)

(6074, 226) (2025, 226) (2025, 226)


In [35]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [36]:
# 회귀분석 객체 생성
mlr = LinearRegression()

# 회귀분석 모델 학습
mlr.fit(x_train, y_train)

LinearRegression()

In [37]:
# 회귀계수 확인
print(mlr.intercept_)
print(mlr.coef_)

0.3843022931277795
[ 3.71387283e-01 -9.06062611e-01 -1.58502205e+00 -1.12402739e-01
 -4.44040736e+00 -2.44097900e-01 -2.78451755e-02  6.08743260e-01
  2.37073024e-01  1.67365523e+01  9.39235464e+00 -2.31493375e+00
  1.36008429e+01 -9.13192557e-02  1.55133778e-02  2.80284270e-01
  3.00303809e-02  1.19551046e+00  3.15783128e-01  6.34987766e+00
 -9.74955129e+00  2.65064799e-01 -1.19385152e+01  4.39016418e+00
 -2.60552226e-02  2.04630596e+01  6.77382543e+00 -5.13607719e+00
 -9.31434674e-01  1.65743520e-01  2.11238177e+01  2.98163786e-01
 -5.36391956e+00  1.22483779e-01  2.77405572e-01 -3.13812150e+00
  1.55733634e+00 -1.03617116e+01 -3.46561517e-01  2.50605755e+01
  3.29450964e-02 -1.89713209e+00 -1.90192703e-01 -8.72515611e-01
  6.62256827e+00  5.54468433e+00 -4.98991709e+00  2.93118596e+00
 -8.18038439e-01  7.67785981e-01  1.61908623e+01  1.94500520e+01
 -2.56269728e+00  1.10857234e+00 -3.67988222e+00 -4.83222670e+00
 -1.68843431e+01  1.04741241e-02  4.04803127e+01 -6.14409311e+00
 -7.41

In [38]:
# training data 예측값
pred_train = mlr.predict(x_train)

In [39]:
# training data에 대한 R-square 계산
from sklearn.metrics import r2_score
print(r2_score(y_train, pred_train))

0.33225740492590217


In [40]:
# validation data에 대한 R-square 계산
pred_val = mlr.predict(x_val)
print(r2_score(y_val, pred_val))

0.28810275366992844


In [41]:
# test data에 대한 R-square 계산
pred_test = mlr.predict(x_test)
print(r2_score(y_test, pred_test))

0.29997494378772604


In [44]:
#전진선택법 

# 선택된 변수들, R-square 값 및 모델 저장
best_variables = []
best_r2 = 0.
best_model = None

# 남아 있는 변수들
remain_variables = list(range(10))

for round in range(10):
    print(f"============ round {round+1} ============")
    r2_of_this_round = []
    models_of_this_round = []

    for var in remain_variables:
        # 사용될 변수들과 모델
        use_vars = best_variables + [var]
        model = LinearRegression()

        # 지정된 변수만 사용하게끔 데이터 추출
        x_train_small = x_train[:, use_vars]
        x_val_small = x_val[:, use_vars]

        # 지정된 변수로 모델 학습
        model.fit(x_train_small, y_train)
        models_of_this_round.append(model)

        # validation R-square 계산
        r2 = r2_score(y_val, model.predict(x_val_small))
        r2_of_this_round.append(r2)
  
    # R-square 가 높은 모델 선택
    best_r2_of_this_round = np.max(r2_of_this_round)

    # 이전 round와 비교
    if best_r2_of_this_round > best_r2:
        best_var_of_this_round = np.argmax(r2_of_this_round)

        # 변수 추가, R-square 값 및 모델 업데이트
        best_variables.append(remain_variables[best_var_of_this_round])
        best_r2 = best_r2_of_this_round
        best_model = models_of_this_round[best_var_of_this_round]

        # 남은 변수들 중 선택된 변수 제거
        remain_variables.pop(best_var_of_this_round)

        print('best variables updated: ', best_variables)
        print('current best r2: ', best_r2)

    # 더 이상 개선되지 않으면 멈춤  
    else:
        print("no improvement")
        break



print('\n---------------------------------------------------\n')
print('final variables: ', sorted(best_variables))
print('final r2: ', best_r2)
  



============ round 1 ============


TypeError: '(slice(None, None, None), [0])' is an invalid key

In [ ]:
print(r2_score(y_test, best_model.predict(x_test[:, best_variables])))

In [ ]:
# test data에 대한 adjust R-square 계산
pred_test = mlr.predict(x_test)
test_r2 = r2_score(y_test, pred_test)
test_adj_r2 = 1-(1-test_r2)*(y_test.shape[0]-1)/(y_test.shape[0]-x_test.shape[1]-1)
print(test_adj_r2)

In [ ]:
#후진제거법
# 선택된 변수들, R-square 값 및 모델 저장
best_variables = list(range(10))
best_adj_r2 = 0.
best_model = None


# 선택된 변수들 중 Adjusted R-square의 손실이 가장 적은 변수를 골라 없애기
for round in range(10):
  print(f"============ round {round+1} ============")
  adj_r2_of_this_round = []
  models_of_this_round = []

  for var in best_variables:
    # 사용될 변수들과 모델
    use_vars = best_variables.copy()
    use_vars.remove(var)
    model = LinearRegression()

    # 지정된 변수만 사용하게끔 데이터 추출
    x_train_small = x_train[:, use_vars]
    x_val_small = x_val[:, use_vars]

    # 지정된 변수로 모델 학습
    model.fit(x_train_small, y_train)
    models_of_this_round.append(model)

    # validation adjusted R-square 계산
    r2 = r2_score(y_val, model.predict(x_val_small))
    adj_r2 = 1 - (1-r2)*(y_val.shape[0]-1)/(y_val.shape[0]-len(use_vars)-1)
    adj_r2_of_this_round.append(adj_r2)
    
  # R-square 가 높은 모델 선택
  best_adj_r2_of_this_round = np.max(adj_r2_of_this_round)

  # 이전 round와 비교
  if best_adj_r2_of_this_round > best_adj_r2:
    max_var = np.argmax(adj_r2_of_this_round)
    best_variables.pop(max_var)
    best_adj_r2 = best_adj_r2_of_this_round
    best_model = models_of_this_round[max_var]

    print('best variables updated: ', best_variables)
    print('current best r2: ', best_adj_r2)

  # 더 이상 개선되지 않으면 멈춤
  else:
    print("no improvement")
    break

print('---------------------------------------------------')
print('final variables: ', sorted(best_variables))
print('final adj_r2: ', best_adj_r2)

print('---------------------------------------------------')
test_r2=r2_score(y_test, best_model.predict(x_test[:, best_variables]))
test_adj_r2 =1-(1-test_r2)*(y_test.shape[0]-1)/(y_test.shape[0]-len(best_variables)-1) 
print('test adjust R-square: ', test_adj_r2)


In [ ]:
#회귀모형 검정
from statsmodels.regression.linear_model import OLS
import statsmodels.api

In [ ]:
sm_model = OLS(y_train, statsmodels.api.add_constant(x_train))

sm_model = sm_model.fit()
print(sm_model.summary())

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
for i in range(x_train.shape[1]):
  print(f"VIF of x{i+1}: {variance_inflation_factor(x_train, i):.2f}")

In [ ]:
# 다중공선성이 확인된 변수들을 제외하고 회귀분석 학습하고 결과 출력하기(statsmodels 이용)
use_variables = [i for i in range(x_train.shape[1]) if variance_inflation_factor(x_train, i) < 10]
small_model = OLS(y_train, statsmodels.api.add_constant(x_train[:, use_variables]))

small_model = small_model.fit()
print(small_model.summary())

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.scatter(pred_train, y_train - pred_train)
plt.plot([pred_train.min(), pred_train.max()], [0, 0], '--', color='grey')

## Regularized Regression - 성능 안좋아 

In [45]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [46]:
# Ridge, Lasso, ElasticNet 모델 객체 생성하기
ridge = Ridge(alpha=0.1)
lasso = Lasso(alpha=0.1)
elastic = ElasticNet(alpha=1.0, l1_ratio=0.5)

In [47]:
# 각 모델 학습하기
ridge.fit(x_train, y_train)
lasso.fit(x_train, y_train)
elastic.fit(x_train, y_train)

ElasticNet()

In [48]:
# Ridge 모델의 training & validation data에 대한 R-square 계산하기
ridge_train_r2 = ridge.score(x_train, y_train)
ridge_val_r2 = ridge.score(x_val, y_val)
print ("Ridge training R-square: %.4f", ridge_train_r2)
print ("Ridge validation R-square: %.4f", ridge_val_r2)

Ridge training R-square: %.4f 0.32793760848693687
Ridge validation R-square: %.4f 0.2926347384395527


In [49]:
# Lasso 모델의 training & validation data에 대한 R-square 계산하기
lasso_train_r2 = lasso.score(x_train, y_train)
lasso_val_r2 = lasso.score(x_val, y_val)
print ("Lasso training R-square:", lasso_train_r2)
print ("Lasso validation R-square: ", lasso_val_r2)

Lasso training R-square: 0.16415783130130268
Lasso validation R-square:  0.15966887158151266


In [50]:
# TODO: ElasticNet 모델의 training & validation data에 대한 R-square 계산하기
elastic_train_r2 = elastic.score(x_train, y_train)
elastic_val_r2 = elastic.score(x_val, y_val)
print ("ElasticNet training R-square:", elastic_train_r2)
print ("ElasticNet validation R-square:: ", elastic_val_r2)

ElasticNet training R-square: 0.0
ElasticNet validation R-square::  -0.00042236721162192126


In [51]:
# 각 모델이 사용한 변수의 개수 세어보기
ridge_used_variables = np.sum(ridge.coef_ != 0)
lasso_used_variables = np.sum(lasso.coef_ != 0)
elastic_used_variables = np.sum(elastic.coef_ != 0)
print("Used variables: Ridge vs Lasso vs ElasticNet = %d vs %d vs %d" % (ridge_used_variables, lasso_used_variables, elastic_used_variables))

Used variables: Ridge vs Lasso vs ElasticNet = 226 vs 5 vs 0


In [52]:
alpha_list = [0.01, 0.1, 1, 10]
for alpha in alpha_list:
    # TODO: 각 alpha를 이용한 Lasso 모델의 training & validation data에 대한 R-square 및 변수 개수 계산하기
    lasso = Lasso(alpha=alpha)
    lasso.fit(x_train, y_train)
    lasso_train_score = lasso.score(x_train, y_train)
    lasso_val_score = lasso.score(x_val, y_val)
    lasso_used_variables = np.sum(lasso.coef_ != 0)
    
    print(f"======================= alpha={alpha} =======================")
    print(f"training score: {lasso_train_score}")
    print(f"test score: {lasso_val_score}")
    print(f"number of features used: {lasso_used_variables}")

======================= alpha=0.01 =======================
training score: 0.23808434475025886
test score: 0.2326275034760361
number of features used: 31
======================= alpha=0.1 =======================
training score: 0.16415783130130268
test score: 0.15966887158151266
number of features used: 5
======================= alpha=1 =======================
training score: 0.0
test score: -0.00042236721162192126
number of features used: 0
======================= alpha=10 =======================
training score: 0.0
test score: -0.00042236721162192126
number of features used: 0


## Logistic Regression -성능 젤 좋아 

In [53]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(x_train, y_train)

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix

pred_train = logistic.predict(x_train)
print(f'training accuracy: {accuracy_score(y_train, pred_train)}')
print(confusion_matrix(y_train, pred_train))

training accuracy: 0.8202173197234113
[[4824    1    0    0    0    1   31   42    5    0    0]
 [  43    4    0    0    0    0    3    1    5    0    0]
 [   7    0    2    0    0    0    1    0    0    0    0]
 [  14    0    0    1    0    0    1    2    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0]
 [  59    0    0    0    0   12    2   12    0    0    0]
 [ 252    1    0    0    0    2   46   20    9    0    0]
 [ 307    0    0    0    0    3   18   74    6    0    0]
 [ 161    0    0    0    0    1   19   11   19    0    0]
 [  26    0    0    0    0    0    1    0    0    0    0]
 [  16    0    0    0    0    0    1    0    2    0    0]]


In [55]:
pred_val = logistic.predict(x_val)
print(f'validation accuracy: {accuracy_score(y_val, pred_val)}')
print(confusion_matrix(y_val, pred_val))

validation accuracy: 0.8232098765432099
[[1631    0    0    0    0    0    7   14    5    0    0]
 [   9    0    0    0    0    0    3    0    0    0    0]
 [   2    0    0    0    0    0    0    0    0    0    0]
 [   3    0    0    0    0    0    0    1    0    0    0]
 [   3    0    0    0    0    0    0    0    0    0    0]
 [  20    0    0    0    0    0    5    6    0    0    0]
 [  86    3    0    0    0    0    9    5    5    0    0]
 [  99    0    0    0    0    3    3   22    1    0    0]
 [  47    1    0    0    0    0    5    3    5    0    0]
 [  13    0    0    0    0    0    0    0    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0]]


In [56]:
pred_test = logistic.predict(x_test)
print(f'test accuracy: {accuracy_score(y_test, pred_test)}')
print(confusion_matrix(y_test, pred_test))

test accuracy: 0.8162962962962963
[[1615    2    0    0    0    0    5   16    1    0    0]
 [  13    1    0    0    0    0    1    0    2    0    0]
 [   1    0    0    0    0    0    1    0    0    0    0]
 [   7    0    0    0    0    0    0    3    0    0    0]
 [   1    0    0    0    0    0    0    1    0    0    0]
 [  15    0    0    0    0    1    2    9    0    0    0]
 [  97    0    0    0    0    0    9    7    3    0    0]
 [  90    0    0    0    0    1    5   26    3    0    0]
 [  50    0    0    0    0    1   11    2    1    0    0]
 [  15    0    0    0    0    0    2    2    0    0    0]
 [   3    0    0    0    0    0    0    0    0    0    0]]


In [57]:
# 경고 문구 없이 로지스틱 회귀분석 학습 완료하기
logistic10000 = LogisticRegression(max_iter=10000)
logistic10000.fit(x_train, y_train)

LogisticRegression(max_iter=10000)

In [58]:
# 학습한 모델의 training, validation, test 정확도 알아보기
new_pred_train = logistic10000.predict(x_train)
print(f'accuracy: {accuracy_score(y_train, new_pred_train)}')
print(confusion_matrix(y_train, new_pred_train))

print('-----------------------------------')
new_pred_val = logistic10000.predict(x_val)
print(f'accuracy: {accuracy_score(y_val, new_pred_val)}')
print(confusion_matrix(y_val, new_pred_val))

print('-----------------------------------')
new_pred_test = logistic10000.predict(x_test)
print(f'accuracy: {accuracy_score(y_test, new_pred_test)}')
print(confusion_matrix(y_test, new_pred_test))

accuracy: 0.8198880474152124
[[4821    1    1    0    0    2   30   43    6    0    0]
 [  43    4    0    0    0    0    3    1    5    0    0]
 [   7    0    2    0    0    0    1    0    0    0    0]
 [  14    0    0    1    0    0    1    2    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0]
 [  60    0    0    0    0   11    2   12    0    0    0]
 [ 252    0    0    0    0    2   47   20    9    0    0]
 [ 306    0    0    0    0    3   18   75    6    0    0]
 [ 162    0    0    0    0    1   18   11   19    0    0]
 [  26    0    0    0    0    0    1    0    0    0    0]
 [  16    0    0    0    0    0    1    0    2    0    0]]
-----------------------------------
accuracy: 0.8232098765432099
[[1631    0    0    0    0    0    7   14    5    0    0]
 [   9    0    0    0    0    0    3    0    0    0    0]
 [   2    0    0    0    0    0    0    0    0    0    0]
 [   3    0    0    0    0    0    0    1    0    0    0]
 [   3    0    0    0    0    0    

## Ensemble

In [60]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

합의기반결합 - Voting

In [61]:
# 모델 객체 생성하기
log_clf = LogisticRegression()
dt_clf = DecisionTreeClassifier(random_state=1)
svm_clf = SVC()

voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), 
                ('dt', dt_clf), 
                ('svc', svm_clf)])

In [62]:
# 각 모델 학습 및 정확도 확인하기
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore")

voting_clf.fit(x_train, y_train)
pred_test = voting_clf.predict(x_test)
print(f'voting accuracy: {accuracy_score(y_test, pred_test)}')

for name, estimator in voting_clf.named_estimators_.items():
  estimator.fit(x_train, y_train)
  pred_test_estim = estimator.predict(x_test)
  print(f'{name}: {accuracy_score(y_test, pred_test_estim)}')

voting accuracy: 0.8108641975308643
lr: 0.8162962962962963
dt: 0.7071604938271605
svc: 0.8093827160493827


In [63]:
# soft voting 방식으로 모델 생성하기
log_clf_2 = LogisticRegression()
dt_clf_2 = DecisionTreeClassifier(random_state=1)
svm_clf_2 = SVC(probability=True)

voting_clf_2 = VotingClassifier(
    estimators=[('lr', log_clf_2), 
                ('dt', dt_clf_2), 
                ('svc', svm_clf_2)],
                voting='soft')

In [64]:
# soft voting 방식으로 생성한 모델 학습하기
voting_clf_2.fit(x_train, y_train)
pred_test_2 = voting_clf_2.predict(x_test)
print(f'soft voting accuracy: {accuracy_score(y_test, pred_test_2)}')

for name, estimator in voting_clf_2.named_estimators_.items():
  estimator.fit(x_train, y_train)
  pred_test_estim = estimator.predict(x_test)
  print(f'{name}: {accuracy_score(y_test, pred_test_estim)}')

soft voting accuracy: 0.7975308641975308
lr: 0.8162962962962963
dt: 0.7071604938271605
svc: 0.8093827160493827


합의기반 결합 -Bagging

In [66]:
tree_clf = DecisionTreeClassifier(random_state=1)
tree_clf.fit(x_train, y_train)
pred_test = tree_clf.predict(x_test)
print(f'accuracy: {accuracy_score(y_test, pred_test)}')

accuracy: 0.7071604938271605


In [67]:
# BaggingClassifier를 사용해 의사결정 나무 분류기 학습 및 정확도 계산하기
from sklearn.ensemble import BaggingClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(random_state=1), n_estimators=300,
    max_samples=500, random_state=1)
bag_clf.fit(x_train, y_train)

pred_test_bag = bag_clf.predict(x_test)
print(f'accuracy: {accuracy_score(y_test, pred_test_bag)}')

accuracy: 0.8103703703703704


In [68]:
# RandomForestClassifier를 사용해 분류기 학습 및 정확도 계산하기
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=300, random_state=1)
rf_clf.fit(x_train, y_train)
pred_test_rf = rf_clf.predict(x_test)
print(f'accuracy: {accuracy_score(y_test, pred_test_rf)}')

accuracy: 0.8098765432098766


In [69]:
from sklearn.model_selection import GridSearchCV

In [70]:
# GridSearchCV를 이용해 최적의 조합을 찾고 그 때의 정확도 계산하기
n_estimators = [100, 200, 300]
max_featrues = ['auto', 0.2, 0.5]
min_samples_leaf = [1, 5]
max_depth = [None, 10]
max_samples = [1000]

param_grid = {'n_estimators' : n_estimators, 'max_features': max_featrues, 
              'min_samples_leaf': min_samples_leaf, 'max_depth': max_depth, 
              'max_samples': max_samples}

rf_grid = GridSearchCV(RandomForestClassifier(), param_grid=param_grid, cv=4, scoring='accuracy')

rf_grid.fit(x_train, y_train)

GridSearchCV(cv=4, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [None, 10],
                         'max_features': ['auto', 0.2, 0.5],
                         'max_samples': [1000], 'min_samples_leaf': [1, 5],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy')

In [71]:
print(rf_grid.best_params_)
pred_test_rf_grid = rf_grid.predict(x_test)
print(f'accuracy: {accuracy_score(y_test, pred_test_rf_grid)}')

{'max_depth': None, 'max_features': 0.2, 'max_samples': 1000, 'min_samples_leaf': 1, 'n_estimators': 300}
accuracy: 0.8093827160493827
